#pragma once

#if !defined(_NTDDK_) && !defined(_WDMDDK_) && !defined(_NTIFS_)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <winioctl.h>
#endif

#define MACROHID_PROTOCOL_VERSION 1
#define MACROHID_MAX_REPORT_SIZE 64

#define MACROHID_KEYBOARD_REPORT_ID 0x01
#define MACROHID_MOUSE_REPORT_ID 0x02
#define MACROHID_CONSUMER_REPORT_ID 0x03

// {7F6E65AB-43E6-4ED1-8F0D-3891D94F6270}
DEFINE_GUID(GUID_DEVINTERFACE_MACROHID,
    0x7f6e65ab, 0x43e6, 0x4ed1, 0x8f, 0x0d, 0x38, 0x91, 0xd9, 0x4f, 0x62, 0x70);

#define FILE_DEVICE_MACROHID 0x8000

#define IOCTL_MACROHID_PING CTL_CODE(FILE_DEVICE_MACROHID, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MACROHID_SUBMIT_REPORT CTL_CODE(FILE_DEVICE_MACROHID, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_MACROHID_GET_STATS CTL_CODE(FILE_DEVICE_MACROHID, 0x803, METHOD_BUFFERED, FILE_READ_DATA)

typedef struct _MACROHID_REPORT_PACKET
{
    ULONG Size;
    ULONG Sequence;
    LARGE_INTEGER HostQpc;
    UCHAR ReportId;
    UCHAR ReportLength;
    UCHAR Report[MACROHID_MAX_REPORT_SIZE];
} MACROHID_REPORT_PACKET, *PMACROHID_REPORT_PACKET;

typedef struct _MACROHID_DRIVER_STATS
{
    ULONG ProtocolVersion;
    ULONG ReportsSubmitted;
    ULONG ReportsRejected;
    ULONG LastNtStatus;
    LARGE_INTEGER LastSubmitQpc;
} MACROHID_DRIVER_STATS, *PMACROHID_DRIVER_STATS;
